apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodb-backup
  namespace: my-namespace
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: mongobackup
            image: myuser/myrepo:mytag
            resources:
              requests:
                cpu: 20m
                memory: 500M
              limits:
                cpu: 60m
                memory: 2000M
            env:
              - name: MONGODB__URI
                valueFrom:
                  secretKeyRef:
                    name: mongodb-connection-string
                    key: connectionstring
              - name: AZURESTORAGE__CONNECTIONSTRING
                valueFrom:
                  secretKeyRef:
                    name: storage-account-connection-string
                    key: connectionstring      
              - name: AZURESTORAGE__BLOBSERVICE
                valueFrom:
                  secretKeyRef:
                    name: storage-account-blob-service
                    key: blobservice
              - name: AZURESTORAGE__CONTAINER
                value: "backup"